# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/vendor/motorola/include \
		-I$(TOP)/vendor/motorola/drivers/input/misc/ets_fod_mmi


ets_fod_mmi-y += etxxx_fp.o

obj-m += ets_fod_mmi.o
