# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/vendor/motorola/include \
		-I$(TOP)/vendor/motorola/drivers/input/touchscreen/raydium_mmi

obj-m := raydium_mmi.o
raydium_mmi-objs += raydium_i2c_ts.o
