# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/vendor/motorola/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/vendor/motorola/drivers/power/mmi_gauge_class


obj-m += mmi_gauge_class.o


